### ISSUE TITLE
Depreciation of Net::IMAP.add_authenticator

### ISSUE THREAD

**Issue by donnelly-consulting** [Mailbutler/mail_xoauth2#2]
When i start the rails app i get gems/mail_xoauth2-1.0.2/lib/mail_xoauth2/imap_xoauth2_authenticator.rb:24: warning: Net::IMAP.add_authenticator is deprecated.  Use Net::IMAP::SASL.add_authenticator instead.
Its a straight swap of the call

**Comment by fjaeger** [comment]
Fixed in version 1.0.3
